apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-api-blue
  namespace: analytics
  labels:
    app: analytics-api
    slot: blue
    version: "stable"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-api
      slot: blue
  template:
    metadata:
      labels:
        app: analytics-api
        slot: blue
        version: "stable"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        fsGroup: 999
      containers:
        - name: analytics-api
          image: chandans12/analytics-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: analytics-config
          env:
            - name: SLOT
              value: "blue"
            - name: APP_VERSION
              value: "stable-blue"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "150m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
